### ISSUE TITLE
 Offset argument contained a NaN value

### ISSUE THREAD

**Issue by Manguelo** [RomanBase/hand_signature#12]
Not sure exactly how to reproduce, but I will occasionally get this error when attempting to convert to an image. As I am signing my line disappears and then I will encounter this error when saving as an image a.k.a `await control.toImage()`. 

This issue goes away if you undo the change where your line disappeared. I believe something is getting set to null along the way.

```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: 'dart:ui/painting.dart': Failed assertion: line 43: '<optimized out>': Offset argument contained a NaN value.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      _offsetIsValid (dart:ui/painting.dart:43:10)
#3      Path.arcToPoint (dart:ui/painting.dart:2051:12)
#4      CubicArc.path
package:hand_signature/src/signature_control.dart:381
#5      PathSignaturePainter.paint.<anonymous closure>.<anonymous closure>
package:hand_signature/src/signature_painter.dart:89
#6      List.forEach (dart:core-patch/growable_array.dart:313:8)
#7      PathSignaturePainter.paint.<anonymous closure>
package:hand_signature/src/signature_painter.dart:87
#8      List.forEach (dart:core-patch/growable_array.dart:313:8)
#9      PathSignaturePainter.paint
package:hand_signature/src/signature_painter.dart:86
#10     HandSignatureControl.toPicture <…>
```

Here is the controller setup and body of my scaffold:

**HandSignatureControl** 
```
final control = HandSignatureControl(
    threshold: 0,
    smoothRatio: 0.65,
    velocityRange: 2,
  );
```

**Body**
```
SafeArea(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Stack(
              fit: StackFit.expand,
              children: [
                HandSignaturePainterView(
                  control: control,
                  color: Colors.blue,
                  maxWidth: 7,
                  type: SignatureDrawType.shape,
                ),
                Stack(
                  alignment: Alignment.bottomLeft,
                  children: [
                    Text(
                      'X',
                      style: TextStyle(
                        fontSize: 50,
                        color: Colors.blue.withOpacity(0.7),
                        fontWeight: FontWeight.w100,
                      ),
                    ).paddingOnly(bottom: 10),
                    Divider(
                      height: 2,
                      thickness: 2,
                      color: Colors.blue.withOpacity(0.7),
                    ),
                  ],
                ).paddingOnly(bottom: 50)
              ],
            ).expanded(),
          ],
        ),
      ),
``` 

found this while looking through the lines in my controller: 
<img width="460" alt="Screen Shot 2021-02-19 at 2 12 50 PM" src="https://user-images.githubusercontent.com/42145136/108550496-a43fe100-72bc-11eb-99b4-c57b7752ae2c.png">

Lmk if there is anything I missed. Happened on an iPhone 12 Pro running iOS 14.4. I'm on Flutter channel stable 1.22.6

**Comment by Manguelo** [comment]
For the mean time I'm able to get around this issue by doing something along these lines: 
```
 HandSignaturePainterView(
     control: control,
     color: color,
     maxWidth: 7,
     onPointerUp: () {
        while (control.lines.any((l) => (l.upEndVector.dx.isNaN || l.upStartVector.dx.isNaN) && !l.isDot)) {
              control.stepBack();
              print('step back');
         }
       },
    type: SignatureDrawType.shape,
),
```

This way I remove any lines that have these `NaN` values within the offset

**Comment by RomanBase** [comment]
Hi I think problem can be zero ``threshold``. When two points are spawned at same location, then calculation error can occur.

Try to set some positive number - like 0.001.

**Comment by Manguelo** [comment]
Ah thanks for the heads up! I'll try that and let you know.

**Comment by RomanBase** [comment]
And with such low ``threshold`` you will lose all benefits of smoothing algorithm. I can recommend something greater then ``1``

**Comment by Manguelo** [comment]
With a threshold of `>1` it works great! Thanks for the help 🙌
